baseURL = "https://StumpedMom.com"
languageCode = "en-us"
publishDir = "docs"
title = "Stumped Mom"
theme = "den"
rssLimit = 20

# font style
googlefonts = ["Comfortaa"]
 fontbody = 'Comfortaa'
 fontcode = 'Comfortaa'

# copyRight, In footer
copyright = "Stumped Mom"

# pagination
pagination = 10
paginatePath = "page"

# service plugins
disqusShortname = "stumpedmom"         # disqus_shortname
googleAnalytics = "UA-128973999-1" # UA-XXXXXXXX-X

#language support
defaultContentLanguage = "en"           # Default language to use
defaultContentLanguageInSubdir = true

#enableRobotsTXT = true
canonifyURLS = true

# Links format
[permalinks]
  posts = "/:year/:month/:day/:slug/"
  categories = "/category/:slug/"      # required
  tags = "/tag/:slug/"                 # required
  pages = "/:slug/"

[author]                     # required
name = "Stumped Mom"

[sitemap]                    # required
  changefreq = "daily"
  priority = 0.7
  filename = "sitemap.xml"

# ------------------------------------- #
# ---- Other Params ------------------- #
# ------------------------------------- #

[params]
  since = "2018" 
	rssFullContent = true

# site info
	keywords = ["StumpedMom", "Blog"]
	description =  "Stumped Mom is here to slay!"
	LogoTitle = "Stumped Mom"
	headerImage = "images/hero_img.jpg"

  showMenuLanguages = true

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"
# ------------------------------------- #
# ---- Related Articles --------------- #
# ------------------------------------- #
[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 50

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = true

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 200

[[related.indices]]
  name = "keywords"
  weight = 150

[[related.indices]]
  name = "tags"
  weight = 100

  [languages.en]
    languageCode = "en"
    languageName = "English"
    contentDir = "content/en"
    weight = 1

 

     [[languages.en.menu.main]]
       name = "Posts"
       weight = 20
       identifier = "posts"
	     url = "category/posts/"

    [[languages.en.menu.social]]
      name = "Twitter"
      weight = 10
      identifier = "twitter"
      url = "https://twitter.com/StumpedMom"

    [[languages.en.menu.Links]]
      name ="Contact"
      weight = 5
      indentifier = "contact"
      url = "/contact/"

   